version: "2.4"
services:  
  postgres:
    image: postgres        
    networks:
      - crm
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
networks:
  crm:
    driver: "bridge"